#!/usr/bin/env zsh

self=$(basename "$0")
dotfiles=($(/bin/ls ./dotfiles| grep -v "$self"))

zshrc=".zshrc"
bashrc=".bashrc"

# setup files
for file in ${dotfiles[@]}; do
    if [[ ! -L "$HOME/.$file" || ! -f "$HOME/.$file"]]; then
        ln -s $(realpath ./dotfiles/$file) "$HOME/.$file"
    fi
done

# activate aliases and set ls colors
activate="source ~/.aliases"
colors='export LS_COLORS="$LS_COLORS:di=1;34:ln=0;93:ex=1;31:"'

if [[ "$SHELL" == "/bin/zsh" ]]; then
    grep -qxF "$activate" "$HOME/$zshrc" || echo "$activate" >> "$HOME/$zshrc"
    grep -qxF "$colors" "$HOME/$zshrc" || echo "$colors" >> "$HOME/$zshrc"
elif [[ "$SHELL" == "/bin/bash" ]]; then
    grep -qxF "$activate" "$HOME/$bashrc" || echo "$activate" >> "$HOME/$bashrc"
    grep -qxF "$colors" "$HOME/$bashrc" || echo "$colors" >> "$HOME/$bashrc"
fi
